// POST LIST
export const LIST_LOADING = 'LIST_LOADING';
export const LIST_SUCCESS = 'LIST_SUCCESS';

// SINGLE POST
export const POST_LOADING = 'POST_LOADING';
export const POST_SUCCESS = 'POST_SUCCESS';

// POST COMMENTS
export const COMMENTS_LOADING = 'COMMENTS_LOADING';
export const COMMENTS_SUCCESS = 'COMMENTS_SUCCESS';

// ACCESS TOKEN
export const ACCESS_LOADING = 'ACCESS_LOADING';
export const ACCESS_SUCCESS = 'ACCESS_SUCCESS';

// AUTH CODE
export const SET_AUTH_RSTR = 'SET_AUTH_RSTR';
export const SET_AUTH_CODE = 'SET_AUTH_CODE';

// COMMON
export const REQUEST_FAILURE = 'REQUEST_FAILURE';