// POST LIST
export const LIST_SUCCESS = 'LIST_SUCCESS';

// SINGLE POST
export const POST_SUCCESS = 'POST_SUCCESS';

// POST COMMENTS
export const COMMENTS_SUCCESS = 'COMMENTS_SUCCESS';

// COMMON
export const REQUEST_STARTED = 'REQUEST_STARTED';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';